### ISSUE TITLE
Can't scale image to fix inside border

### ISSUE THREAD

**Issue by erinmilling** [erinmilling/dsn1674-assignment-4#1]
![screen shot 2015-01-30 at 8 58 06 pm](https://cloud.githubusercontent.com/assets/10464609/5986351/d68110dc-a8c2-11e4-9366-3277005254fb.png)
![screen shot 2015-01-30 at 8 58 37 pm](https://cloud.githubusercontent.com/assets/10464609/5986353/e3a6e3f4-a8c2-11e4-95a5-48088b2ff4f6.png)

@thomasjbradley

**Comment by erinmilling** [comment]
nevermind I figured it out:)

**Comment by thomasjbradley** [comment]
Close the issue with the button below please.
